name: Deploy Documentation on Release

on:
  workflow_dispatch:

jobs:
  docs:
    uses: Billingegroup/release-scripts/.github/workflows/_publish-docs-on-release.yml@v0
    with:
      project: scikit-zhangt20-lvl5
      c_extension: false
      headless: false
